# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagens', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
        migrations.AlterField(
            model_name='project',
            name='date_ini',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='num_phase',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
