# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 12:39
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagens', '0002_auto_20170808_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique_with=('project',)),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique_with=('date_ini',)),
        ),
    ]
