# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 01:37
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagens', '0003_auto_20170809_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='prova', editable=False, populate_from='name', unique_with=('date_upload',)),
        ),
        migrations.AlterField(
            model_name='image',
            name='coord_left',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='image',
            name='coord_right',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='image',
            name='date_upload',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(upload_to='img'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='name',
            field=models.CharField(choices=[('step1', 'Paso 1'), ('step2', 'Paso 2'), ('step3', 'Paso 3')], max_length=5),
        ),
    ]
