# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagens', '0007_image_thumb_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='thumb_img',
        ),
        migrations.AddField(
            model_name='image',
            name='img_bordes',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='img_diseno',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='img_values',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
