# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-30 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imagens', '0008_auto_20171016_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edge',
            name='phase_ptr',
        ),
        migrations.RemoveField(
            model_name='phase',
            name='project',
        ),
        migrations.RemoveField(
            model_name='image',
            name='coord_left',
        ),
        migrations.RemoveField(
            model_name='image',
            name='coord_right',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='edge',
        ),
        migrations.AddField(
            model_name='parameter',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='imagens.Image'),
        ),
        migrations.DeleteModel(
            name='Edge',
        ),
        migrations.DeleteModel(
            name='Phase',
        ),
    ]
