# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-03 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagens', '0011_auto_20180102_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='bool_depth',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='image',
            name='bool_high',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='image',
            name='bool_width',
            field=models.BooleanField(default=True),
        ),
    ]
