# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-11 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '__first__'),
        ('imagens', '0014_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.CustomUser'),
            preserve_default=False,
        ),
    ]
